---
#
# Select what to install by specifying a tag
# - backend - to install backend
# - frontend - to install frontend
#
- name: Deploy/Undeploy Application Backend
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  environment:
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    AWS_ACCESS_KEY: "{{ aws_access_key }}"

  tasks:

    - name: Load external variables from a file
      include_vars:
        file: demoapp_ansible_vars.yml
      tags:
        - always

    ##
    ## Install backend or/and frontend
    ##
    - name: Install application
      block:

        - import_tasks: install_backend.yml
          vars:
            base_dir: "../demoapp/"
        - meta: end_play

      rescue:

        - import_tasks: uninstall_backend.yml
          tags: [ "backend" ]
        - meta: end_play

      when: do in [ "install" ]


    ##
    ## Uninstall backend or/and frontend
    ##
    - name: Uninstall application backend
      block:

        - import_tasks: uninstall_backend.yml
          tags: [ "backend" ]
        - meta: end_play

      when: do in [ "uninstall" ]





