---
##
## The playbook runs provided tasks on localhost.
## Accepted variables:
## - tasks_dir - path to the tasks dir (default: demo_1)
## - tasks_file - file in the infra_tasks_dir (must be provided)
## - infra_vars_file - file with variables for infra
##
## This playbook might be used as ad-hoc (for localhost only) or for any inventories
## in Ansible Tower
##
- name: Run tasks on localhost
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  environment:
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
  vars:
    l_tasks_dir: "{{ tasks_dir | default('infra') }}"
    l_tasks_file: "{{ tasks_file }}"
    l_infra_vars_file: "{{ infra_vars_file | default(l_tasks_dir + '/vars_aws-vpc.yml')}}"

  tasks:


    - name: Check that the tasks_file is provided
      assert:
        that:
          - l_tasks_file is defined
          - l_tasks_file != ""
          - l_infra_vars_file is defined
          - l_infra_vars_file != ""
        fail_msg: "Tasks file and Infra vars file must be provided"
        success_msg: |
          Provided tasks file is {{ l_tasks_file }}, tasks dir is {{ l_tasks_dir }}. Infra vars file is {{ l_infra_vars_file }}.


    - name: Include infra vars
      include_vars:
        file: "{{ l_infra_vars_file }}"


    - name: Run tasks from the provided tasks_file
      include_tasks: "{{ l_tasks_dir }}/{{ item }}"
      loop: "{{ l_tasks_file.split(',') }}"

