---
##
## The playbook runs provided tasks on provided hosts
## Accepted variables:
## - tasks_dir - path to the tasks dir (default: infra)
## - tasks_file - file in the infra_tasks_dir (must be provided)
##
- name: Run tasks on hosts from inventory
  hosts: "{{ run_on_hosts }}"
  gather_facts: false
  become: false
  environment:
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
  vars:
    # tasks_dir: "{{ tasks_dir | default('infra') }}"
    # tasks_file: "{{ tasks_file }}"

  tasks:


  - name: Check that the tasks_file is provided
    assert:
      that:
        - tasks_file is defined
      fail_msg: "Tasks file must be provided"
      success_msg: "Provided tasks file is {{ tasks_file }}, tasks dir is {{ tasks_dir }}"


  - name: Run tasks from the provided tasks_file
    import_tasks: "{{ tasks_dir }}/{{ tasks_file }}"

